// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovmldtiwaeffsdyremnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bWxkdGl3YWVmZnNkeXJlbW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDM5ODUsImV4cCI6MjA2Njg3OTk4NX0.LpTbC9lcsyPGYHvx2VQoeQqwQyA2GcvfwrQ4b_owSLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});